using NUnit.Framework;
using Polymarket.Net.Enums;
using Polymarket.Net.Objects;

namespace Polymarket.Net.UnitTests
{
    /// <summary>
    /// Byte-for-byte parity tests for the ERC-7739 wrapped ClobAuth L1 signature
    /// used by deposit-wallet (POLY_1271) accounts. The expected value was
    /// generated by an independent Python implementation (eth_account + keccak)
    /// of the same envelope: innerSig(65) || clobAuthDomainSep(32) ||
    /// contentsHash(32) || CLOB_AUTH_TYPE_STRING || uint16_be(len).
    /// </summary>
    [TestFixture]
    public class ClobAuth1271SigningTests
    {
        private const string OwnerPrivateKey = "0x1111111111111111111111111111111111111111111111111111111111111111";
        private const string DepositWallet = "0x6DdcAD7425B4D92b930F8Ae200Af90Ce60B79E29";

        private const string ExpectedWrappedSignature =
            "0x38226be50c1ea18ebb1208693e8525e25c01657ecfa638ed500a3b661846267122c29534bb045de5" +
            "78ce47a0b22c8bf2c9d30b708c44bed989282a03af129bf81bcfc66be2a3b30464cb3b588324101f6" +
            "60c9a205fa76e8e5f83ee16a528e1c4cb631b23a7ccc7f3f229edc5e855633f15fe96b081636b4685" +
            "8e5c977961313fd6436c6f6241757468286164647265737320616464726573732c737472696e6720" +
            "74696d657374616d702c75696e74323536206e6f6e63652c737472696e67206d6573736167652900" +
            "47";

        [Test]
        public void WrappedClobAuthSignature_MatchesPythonReference()
        {
            var creds = new PolymarketCredentials(SignType.Poly1271, OwnerPrivateKey, DepositWallet)
            {
                WalletBoundL1Auth = true
            };
            var auth = new PolymarketAuthenticationProvider(creds);

            var sig = auth.GetClobAuthSignaturePoly1271("1700000000", 0, 137);

            Assert.That(sig, Is.EqualTo(ExpectedWrappedSignature));
        }

        [Test]
        public void WrappedClobAuthSignature_IsDeterministic()
        {
            var creds = new PolymarketCredentials(SignType.Poly1271, OwnerPrivateKey, DepositWallet)
            {
                WalletBoundL1Auth = true
            };
            var auth = new PolymarketAuthenticationProvider(creds);

            var sig1 = auth.GetClobAuthSignaturePoly1271("1700000000", 0, 137);
            var sig2 = auth.GetClobAuthSignaturePoly1271("1700000000", 0, 137);

            Assert.That(sig1, Is.EqualTo(sig2));
        }
    }
}
